### ISSUE TITLE
Error when running "cmake -B build -DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by ghost** [nightmareci/HeborisC7EX-SDL2#1]
When i run cmake -B build -DCMAKE_BUILD_TYPE=Release I get an error.

This is my console:

-- Found PkgConfig: C:/mingw64/bin/pkg-config.exe (found version "0.26")
-- Checking for module 'sdl2'
--   No package 'sdl2' found

**Comment by nightmareci** [comment]
Try the following to install the dependencies in your MSYS2 environment:
```sh
pacman -Syu mingw-w64-SDL2 mingw-w64-SDL2_mixer mingw-w64-SDL2_image mingw-w64-physfs
```
In general, it's best to fully delete a failed/broken CMake build, before retrying:
```sh
rm -r build
```
Then you can try again.

**Comment by ghost** [comment]
Im on windows

**Comment by ghost** [comment]
Oh wait nvm ok ill try when im on my computer

**Comment by nightmareci** [comment]
@Derpez I updated the readme with MSYS2 instructions I've fully tested as working, the comment I posted previously here was incorrect and won't work.
