### ISSUE TITLE
Bug: TOMOYO-TI mode doesn't work on RK3266 based consoles

### ISSUE THREAD

**Issue by ghost** [nightmareci/HeborisC7EX-SDL2#20]
When you choose TOMOYO-TI mode it automatically shows you that you won ;-)
https://www.dropbox.com/s/8xkwt4xirhjakyv/heboris.JPG?dl=0

Run it on Anbernic RG351MP on Amberelec and JELOS.

**Comment by nightmareci** [comment]
The latest commit works fine for me on Manjaro Linux in TOMOYO-TI, and I don't have that device, so I'm not sure what I can do for you. Are you using the very latest code?

**Comment by ghost** [comment]
Sorry. I am user, not programmer. Guys from Amberelec compiled it for me. They forgot copy mission and stage folders in config folder. I thought this is a reason. I copied by myself but it still didn't work. Is all what required for this mode?
Here is their "package" for my device: https://www.dropbox.com/s/pqustf6mvmpmbv1/Heboris-sdl-RG351MP.zip?dl=0

**Comment by nightmareci** [comment]
This sounds very much like a bug with how they're producing the package, and not my concern. It works perfectly fine for me on my system. Take up the issue with them. I'm not currently providing any support specific to that device, they did all the porting without contacting me at all. The only thing that I think could be the issue has to do with how files are loaded with PhysicsFS (libphysfs.so.1), you could try letting those guys know that, but without the device I can't test/fix anything myself.

If I had that device, I'd try officially supporting it myself, but I don't have the device, so I can't provide such support.

**Comment by ghost** [comment]
OK. No worries. Thanks anyway. And thanks for your efforts to porting such great game to SDL2 ;-)

**Comment by zaphod77** [comment]
stage00.sav is the one for tomoyo-ti first level.  test the other tomoyo versions. also make sure the the files are lowercase.
