### ISSUE TITLE
Feature Request: Support for unique Next-Piece Sounds

### ISSUE THREAD

**Issue by michaelbutler** [nightmareci/HeborisC7EX-SDL2#24]
I didn't see this in `se.txt` so I assume it was never implemented. It would be cool to have support for unique next-piece sound effects if present in the `res/se` folder. e.g. next_j, next_l, next_i, next_s, next_z and so on. 

Other clones have support for this but name the files next_green, next_blue, etc. but since heboris supports so many rotation systems and the colors can change, it would be better to name them by the shape.

**Comment by nightmareci** [comment]
It does support next piece sounds, provided in `res/se/block#.wav`, with `#` being a number from 1 to 7. I'm not sure what the correspondence between numbers and pieces is.

**Comment by michaelbutler** [comment]
@nightmareci thanks I will try that. I did see it in the notes but it explained it as when "a block is placed" but it could be a Japanese translation error.

```
block1.wav		: this sounds when a block is placed. 
(These block sounds cycle around)
```

So I assumed it was something else.

**Comment by nightmareci** [comment]
@michaelbutler I think "when a block is placed" makes sense, though it's a bit confusing. The preview sound is played after you place a piece. The confusion I think comes from it being worded around the active piece, not the next piece.
